[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
opacity = 0.9
startup_mode = "Maximized"
decorations = "None"

[window.padding]
x = 10
y = 10

[colors]
# transparent_background_colors = true
